name: longshot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - libgcc=15.2.0=he0feb66_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libstdcxx=15.2.0=h934c35e_16
  - libzlib=1.3.1=hb9d3cd8_2
  - longshot=1.0.0=h8dc4d9d_3
prefix: /users/2564983r/.conda/envs/longshot
