name: ngsutils
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2019.11.28=py27h8c360ce_1
  - coverage=5.0.4=py27hdf8410d_0
  - eta=0.9.7=pyh864c0ab_3
  - htslib=1.17=h6bc39ce_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.5=h2d0b736_3
  - ngsutils=0.5.9=py27h9801fc8_5
  - openssl=1.1.1w=hd590300_0
  - pip=20.1.1=pyh9f0ad1d_0
  - pysam=0.20.0=py27h7835474_0
  - python=2.7.15=h5a48372_1011_cpython
  - python_abi=2.7=1_cp27mu
  - readline=8.2=h8c095d6_2
  - samtools=1.18=hd87286a_0
  - setuptools=44.0.0=py27_0
  - sqlite=3.46.0=h6d4b2fc_0
  - swalign=0.3.4=py_1
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
prefix: /users/2564983r/.conda/envs/ngsutils
