name: phase_ont
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.11=hd590300_1
  - any2fasta=0.4.2=hdfd78af_3
  - argtable2=2.13=hd590300_1004
  - bc=1.07.1=h7f98852_0
  - bcftools=1.21=h8b25389_0
  - bedtools=2.31.1=hf5e1c6e_2
  - blast-legacy=2.2.26=hf7ff83a_5
  - bwa=0.7.18=he4a0461_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - clustalo=1.2.4=h503566f_10
  - clustalw=2.1=h9948957_12
  - consan=1.2=h7b50bb2_7
  - curl=8.8.0=he654da7_1
  - dendropy=5.0.8=pyhdfd78af_1
  - dialign-tx=1.0.2=h7b50bb2_8
  - dnspython=2.8.0=pyhcf101f3_0
  - expat=2.7.3=hecca717_0
  - famsa=2.2.3=h9948957_1
  - fasttree=2.2.0=h7b50bb2_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freebayes=1.3.6=hb0f3ef8_5
  - freetype=2.12.1=h267a509_2
  - gawk=5.3.1=hcd3d067_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.11=he7cfd77_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - harfbuzz=9.0.0=hfac3d4d_0
  - hmmer=3.4=hb6cb901_4
  - htslib=1.21=h5efdd21_0
  - icu=73.2=h59595ed_0
  - k8=1.2=h6618dc6_3
  - kalign2=2.04=h7b50bb2_8
  - kernel-headers_linux-64=4.18.0=he073ed8_9
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_4
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.25.1=h3f43e3d_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.8.0=hca28451_1
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.80.2=hf974151_0
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=h5347b49_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - mafft=7.526=h4bc722e_0
  - minimap2=2.28=he4a0461_3
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - muscle=3.8.1551=h9948957_9
  - mustang=3.2.4=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.10.1=h4a9d5aa_0
  - openjdk=22.0.1=hb622114_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.6.0=h26f9b46_0
  - p11-kit=0.25.3=he72ba39_0
  - paml=4.10.9=h7b50bb2_1
  - parallel=20251122=ha770c72_0
  - pasta=1.9.2=py312hccd54bf_5
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-algorithm-diff=1.201=pl5321hd8ed1ab_0
  - perl-b-cow=0.007=pl5321hb9d3cd8_1
  - perl-base=2.23=pl5321hd8ed1ab_0
  - perl-bio-asn1-entrezgene=1.73=pl5321hdfd78af_3
  - perl-bio-coordinate=1.007001=pl5321hdfd78af_3
  - perl-bio-featureio=1.6.905=pl5321hdfd78af_4
  - perl-bio-samtools=1.43=pl5321he4a0461_4
  - perl-bio-searchio-hmmer=1.7.3=pl5321hdfd78af_0
  - perl-bio-tools-phylo-paml=1.7.3=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl5321hdfd78af_5
  - perl-bioperl=1.7.8=hdfd78af_1
  - perl-bioperl-core=1.7.8=pl5321hdfd78af_1
  - perl-bioperl-run=1.007003=pl5321hdfd78af_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-class-data-inheritable=0.09=pl5321ha770c72_0
  - perl-clone=0.46=pl5321hb9d3cd8_1
  - perl-compress-raw-bzip2=2.214=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.214=pl5321h4dac143_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-data-dump=1.25=pl5321h7b50bb2_2
  - perl-data-dumper=2.183=pl5321hb9d3cd8_1
  - perl-db_file=1.858=pl5321hb9d3cd8_0
  - perl-devel-stacktrace=2.04=pl5321h296ab09_0
  - perl-digest-hmac=1.05=pl5321hdfd78af_0
  - perl-digest-md5=2.59=pl5321hb9d3cd8_3
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-exception-class=1.45=pl5321ha770c72_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-listing=6.16=pl5321hdfd78af_0
  - perl-file-slurper=0.014=pl5321hdfd78af_0
  - perl-file-sort=1.01=pl5321hdfd78af_3
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-getopt-long=2.58=pl5321hdfd78af_0
  - perl-html-parser=3.81=pl5321h4ac6f70_1
  - perl-html-tagset=3.24=pl5321hdfd78af_0
  - perl-http-cookiejar-lwp=0.014=pl5321hdfd78af_0
  - perl-http-cookies=6.11=pl5321hdfd78af_0
  - perl-http-daemon=6.16=pl5321hdfd78af_0
  - perl-http-date=6.06=pl5321hdfd78af_0
  - perl-http-message=7.01=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.075=pl5321hd8ed1ab_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-tty=1.20=pl5321hb9d3cd8_3
  - perl-ipc-run=20250809.0=pl5321hdfd78af_0
  - perl-libwww-perl=6.81=pl5321hdfd78af_0
  - perl-libxml-perl=0.08=pl5321hdfd78af_3
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-lwp-protocol-https=6.14=pl5321hdfd78af_1
  - perl-mime-base64=3.16=pl5321hb9d3cd8_3
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-module-load=0.34=pl5321hdfd78af_0
  - perl-mozilla-ca=20250602=pl5321hdfd78af_0
  - perl-net-http=6.24=pl5321hdfd78af_0
  - perl-net-ssleay=1.92=pl5321hf14f497_1
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-socket=2.027=pl5321h5c03b87_6
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-sub-uplevel=0.2800=pl5321hb9d3cd8_0
  - perl-test-deep=1.130=pl5321hd8ed1ab_0
  - perl-test-differences=0.72=pl5321ha770c72_0
  - perl-test-exception=0.43=pl5321hd8ed1ab_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-most=0.38=pl5321hdfd78af_0
  - perl-test-needs=0.002009=pl5321hd8ed1ab_0
  - perl-test-requiresinternet=0.05=pl5321hdfd78af_1
  - perl-test-warn=0.37=pl5321hd8ed1ab_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-text-diff=1.45=pl5321hd8ed1ab_0
  - perl-time-local=1.35=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-tree-dag_node=1.35=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-uri=5.34=pl5321ha770c72_0
  - perl-url-encode=0.03=pl5321h9ee0642_1
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-xml-dom=1.46=pl5321hdfd78af_1
  - perl-xml-dom-xpath=0.14=pl5321hdfd78af_2
  - perl-xml-parser=2.44_01=pl5321hf2e2c51_1004
  - perl-xml-regexp=0.04=pl5321hdfd78af_3
  - perl-xml-xpathengine=0.14=pl5321hdfd78af_3
  - phylip=3.697=h7b50bb2_3
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - poa=2.0=h7b50bb2_6
  - prank=170427=h9948957_1
  - probcons=1.12=h8b12597_1
  - probconsrna=1.10=h9f5acd7_4
  - proda=1.0=h503566f_7
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pymongo=4.15.5=py312h1289d80_0
  - python=3.12.3=hab00c5b_0_cpython
  - python_abi=3.12=8_cp312
  - raxml=8.2.13=h7b50bb2_3
  - readline=8.3=h853b02a_0
  - samclip=0.4.0=hdfd78af_1
  - samtools=1.20=h50ea8bc_1
  - sap=1.1.3=h7b50bb2_5
  - seqkit=2.12.0=he881be0_0
  - seqtk=1.4=he4a0461_2
  - setuptools=80.9.0=pyhff2d567_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - snippy=4.6.0=hdfd78af_6
  - snp-sites=2.5.1=he4a0461_5
  - snpeff=5.0=hdfd78af_3
  - sysroot_linux-64=2.28=h4ee821c_9
  - t-coffee=13.46.2.7c9e712d=pl5321hb2a3317_0
  - tabixpp=1.1.0=hce60e53_13
  - tk=8.6.13=noxft_h4845f30_101
  - tmalign=20170708=h8d36177_7
  - tzdata=2025c=h8577fbf_0
  - vcflib=1.0.2=ha025227_6
  - viennarna=2.7.0=py312pl5321h9f0f9fd_0
  - vt=0.57721=h064f3d2_11
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - edlib==1.3.9.post1
      - filelock==3.20.1
      - fsspec==2025.12.0
      - h5py==3.15.1
      - idna==3.11
      - importlib-metadata==8.7.0
      - intervaltree==3.1.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - medaka==2.2.0
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - ont-fast5-api==4.1.3
      - ont-mappy==2.28
      - ont-parasail==1.3.4
      - orjson==3.11.5
      - packaging==25.0
      - progressbar33==2.4
      - pyabpoa==1.5.5
      - pycparser==2.23
      - pysam==0.23.0
      - pyspoa==0.3.2
      - pyvers==0.1.0
      - requests==2.32.5
      - sortedcontainers==2.4.0
      - sympy==1.14.0
      - tensordict==0.10.0
      - toml==0.10.2
      - torch==2.9.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - wurlitzer==3.1.1
      - zipp==3.23.0
prefix: /users/2564983r/.conda/envs/phase_ont
