name: seqtk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libzlib=1.2.13=h4ab18f5_6
  - seqtk=1.3=he4a0461_6
  - zlib=1.2.13=h4ab18f5_6
prefix: /users/2564983r/.conda/envs/seqtk
